### ISSUE TITLE
Fatal error when editing code

### ISSUE THREAD

**Issue by lselden** [tomas-wrobel/scrap#158] opened 2024-12-02 20:06 UTC
First off, nice work so far! I was just trying this out but got stuck in trying out the code functionality - I thought I could start updating the code with standard typescript but the parser complains, then gets stuck without letting you fix anything.

To Reproduce:
```ts
// ⬆️ when I switch to Blocks I get an error and it doesn't return me here to cure the issue
interface Variables {
	"My variable": number;
}

function getRightNow(): number {
    // apparently Date isn't the standard javascript date?!?
	return new Date().getTime()
}

self.whenFlag(() => {
	self.variables["My variable"] = getRightNow();
	self.say(self.variables["My variable"]);
});
```

![image](https://github.com/user-attachments/assets/a806944f-ebde-4273-b3e2-1b2a60b4612a)

![image](https://github.com/user-attachments/assets/a1c0d3be-6cd6-4fe0-938a-1bedc0998d71)

![image](https://github.com/user-attachments/assets/82b93cbf-22bf-4b7f-bfd7-1e51f92fcd92)

**Comment by tomaswrobel** [comment] 2024-12-02 20:20
This is intended. As you stated correctly, Date objects are **not** standard ECMAScript Date.

Codename ScrapScript is an essential part of Scrap, and its job is to make block-compatible ECMAScript subset (meaning not all the features are available).

To comment on your specific need, `Date.prototype.getTime()` has actually the same exact result of `Date.prototype.valueOf()`. To get the numeric result of `Object.protototype.valueOf()`, in the standard JavaScript you can use not only the method itself, but both `+object` and `Number(object)`. Scrap's compiler should handle both cases. 

I'm fully aware this is not a great solution, however I need some friends into team, and want to make some learning material, but I do not have a time.

Current ES subset is defined as this:
```ts

// For TypeScript to work
declare interface RegExp {}
declare interface Boolean {}
declare interface Object {}
declare interface Function {}
declare interface IArguments {}

// Scrap's primitives
declare interface Number {}

/**
 * Converts the value to a number
 * @param value any value
 */
declare function Number(value: any): number;

/**
 * True is converted to 1
 */
declare function Number(value: true): 1;

/**
 * False is converted to 0
 */
declare function Number(value: false): 0;

/**
 * Converts the value to a number
 * @param value True is converted to 1, false to 0
 */
declare function Number(value: boolean): 0 | 1;

declare interface String extends Iterable<string> {
	/**
	 * Bracket notation finds a character by index;
	 * indexes start at zero.
	 */
	readonly [i: number]: string;
	/**
	 * Makes a substring
	 * @param start Zero-based index
	 * @param end Zero-based index
	 */
	slice(start: number, end: number): string;
}

/**
 * Converts the value to a string
 * @param value any value
 */
declare function String<const T>(
	value: T
): T extends number | boolean | string ? `${T}` : string;

// Scrap's iterables
declare interface Symbol {}
declare namespace Symbol {
	const iterator: unique symbol;
	type iterator = typeof iterator;
}

declare interface Iterable<T> {
	/**
	 * Length describes the size of iterable.
	 * It is immutable.
	 *
	 * ```ts
	 * const a = [4, "a", 6];
	 * a.length == 3;
	 *
	 * const b = "Hello";
	 * b.length === 5;
	 * ```
	 */
	readonly length: number;
	/**
	 * Bracket notation finds an element by index;
	 * indexes start at zero.
	 */
	[i: number]: T;
	/**
	 * Checks if string / array includes substring / element
	 * @param item
	 */
	includes(item: T): boolean;
	/**
	 * Finds the zero-based index
	 * Returns -1 if not found.
	 */
	indexOf(item: T): number;

	[Symbol.iterator](): {
		next(): {
			value: T;
		};
	};
}

declare interface Array<T = any> extends Iterable<T> {
	/**
	 * Joins the string represantation with the separator
	 *
	 * ```ts
	 * [3, [1, 2, "A"], "OK", new Date()].join(" - ") === "3 - 1,2,A - OK - 07-24-2050"
	 * ```
	 *
	 * @param separator A comma for example
	 */
	join(separator: string): string;

	/**
	 * Reverses the array and returns it.
	 */
	reverse(): T[];
	/**
	 * Makes a substring
	 * @param start Zero-based index
	 * @param end Zero-based index
	 */
	slice(start: number, end: number): T[];
}

declare const Array: {
	/**
	 * Single type array
	 */
	new <T>(...items: T[]): T[];
	/**
	 * Fixed-sized & Mixed type array - automatically infers the type
	 *
	 * If you want to specify the type, use `new Array<T>(...)`
	 * ```ts
	 * const a = Array(3, "a", 6); // a: [3, "a", 6]
	 * const b = Array<number | string>(3, "a", 6); // b: (number | string)[]
	 * ```
	 */
	new <const T extends any[]>(...items: T): T;
};

declare interface Date {
	/**
	 * Returns the year of the specified date according to local time.
	 */
	getFullYear(): number;

	/**
	 * Returns the month of the specified date according to local time.
	 */
	getMonth(): number;

	/**
	 * Returns the day of the month for the specified date according to local time.
	 */
	getDate(): number;

	/**
	 * Returns the day of the week for the specified date according to local time.
	 */
	getDay(): number;

	/**
	 * Returns the hour for the specified date according to local time.
	 */
	getHours(): number;

	/**
	 * Returns the minutes in the specified date according to local time.
	 */
	getMinutes(): number;

	/**
	 * Returns the seconds in the specified date according to local time.
	 */
	getSeconds(): number;
}

declare const Date: {
	/**
	 * Creates a new date object,
	 * representing the specified date and time
	 * @param date date string
	 */
	new (date: string): Date;

	/**
	 * Creates a new date object,
	 * representing the current date and time
	 */
	new (): Date;
};

declare const Math: {
	/**
	 * Returns a random number between 0 (inclusive) and 1 (exclusive)
	 */
	random(): number;

	/**
	 * Returns the smallest integer greater than or equal to a number
	 */
	floor(value: number): number;

	/**
	 * Returns the largest integer less than or equal to a number
	 */
	ceil(value: number): number;

	/**
	 * Returns the value of a number rounded to the nearest integer
	 */
	round(value: number): number;

	/**
	 * Returns the absolute value of a number
	 * |x| = x if x > 0
	 * |x| = -x if x < 0
	 * |0| = 0
	 */
	abs(value: number): number;

	/**
	 * Returns the square root of a number
	 */
	sqrt(value: number): number;

	/**
	 * Returns the value of x to the power of y
	 */
	sin(value: number): number;

	/**
	 * Returns the value of x to the power of y
	 */
	cos(value: number): number;

	/**
	 * Returns the value of x to the power of y
	 */
	tan(value: number): number;

	/**
	 * Returns the value of x to the power of y
	 */
	asin(value: number): number;

	/**
	 * Returns the value of x to the power of y
	 */
	acos(value: number): number;

	/**
	 * Returns the value of x to the power of y
	 */
	atan(value: number): number;

	/**
	 * Returns the value of x to the power of y
	 */
	log(value: number): number;

	/**
	 * Returns the value of x to the power of y
	 */
	exp(value: number): number;

	/**
	 * Returns the value of x to the power of y
	 */
	log10(value: number): number;
};

declare const window: {
	/**
	 * Displays the native alert dialog with the specified message.
	 * @param message the message to display
	 */
	alert(message: string): void;

	/**
	 * Displays the native confirm dialog with the specified message.
	 * @param message the message to display
	 */
	confirm(message: string): boolean;

	/**
	 *
	 * @param message the message to display
	 */
	prompt(message: string): string;
};

declare const Infinity: number;
declare const NaN: number;
```

Even `undefined` is missing, and many interfaces has no properties at all.

**Comment by tomaswrobel** [comment] 2024-12-02 20:22
But I agree, Date#getTime is a part of ES that **should** be added to the subset, and can be compiled into Number(...).

**Comment by lselden** [comment] 2024-12-02 22:13
Sure, that makes sense! I know I'm not the target audience. I assumed I'd be able to write [blocklike](https://www.blocklike.org/) code rather than it being a subset of the language features.

This issue is actually a couple of separate reports:

* UI bug - If you click on "Blocks" tab while you have a script syntax error it gets the view stuck in a "Compiling code..." overlay, and you can't leave without refreshing. Microsoft PXT handles that same kind of problem by prompting you to "keep editing in javascript" or "discard my changes"
* Didn't know that not all JS features are supported - which is fine
* In general `Date` seems to misbehave - This construction will cause an error if you switch between the code tab and blocks tab: 
![image](https://github.com/user-attachments/assets/5456b439-1f43-434f-9691-f51722980a29) 
* I also noticed that putting parenthesis around an expression could cause drama - I get `SyntaxError: Unsupported node type ParenthesisExpression. Type must be one of void, number, string, boolean, Color, Array, Sprite, Date`

**Comment by tomaswrobel** [comment] 2024-12-02 23:32
Well, of course blocklike is a solution. In fact, Scrap Engine is built on top of it :-). If you can write code in blocklike, Scrap doesn't provide you with any valuable features, maybe TypeScript. The fix for the UI bug is about to be delivered. In fact, all of the troubles you described are now fixed. 

- ParenthesisExpression should not be included in AST at all, but as I switched from Babel to SWC, some things have changed. **Fixed**
- The UI freeze was caused by catching an error twice, well the throwing error is not about displaying the dialog but stopping execution. I messed this up last release with `@load` decorator. **Fixed**
- The `today` is type of Date, whereas `My variable` is type of number. You cannot interchange types :-). The connection checker does its best, but it cannot handle everything. I'm still limited to Blockly's features. **Leaving as it is for now.**
- "All JavaScript" could be supported, but while Scrap is still block-first, this won't be implemented. **Leaving as it is for now.**

As I fixed all the bugs, I close the issue. If you can write JavaScript code, wouldn't you like to improve Scrap? Or do you know somebody who might want to?

> [!NOTE]
> I'm not MIT team for Scratch, I'm not Microsoft team for PXT, I'm an 
> 18-year-old student, so obviously, without even having time to maintain 
> the project, it's full of bugs and limitations.

---

## [6.1.1] - 2024-12-3

### Fixed

- UI freeze when switching from bad code ([#158](https://github.com/tomaswrobel/scrap/issues/158))
- Assigning with `+=`, `-=`, `*=`, `/=`, `%=`, `**=`, `<<=`, `>>=`, `>>>=`, `&=`, `|=`, `^=`
- ParenthesisExpression causes errors in the compilation ([#158](https://github.com/tomaswrobel/scrap/issues/158))

### Added

- Support for `getTime` and `valueOf` methods in `Date` ([#158](https://github.com/tomaswrobel/scrap/issues/158))
- Support for `toString` and `valueOf` methods in `Object`

### Changed

- dependencies update

**Closed as completed by tomaswrobel** 2024-12-02 23:32 UTC

**Comment by lselden** [comment] 2024-12-03 02:56
Great! I'm just exploring options for programming with my kid - I want to be able to write underlying code then be able to work out the "fun" stuff in blocks with him. Your editor is a good idea and nicer than having to copy+paste code into turbowarp as an extension. If I have any input I'll open an issue/pull request.
